apiVersion: batch/v1
kind: Job
metadata:
  name: cp4ba-healthcheck-patterns
  namespace: cp4ba
spec:
  template:
    spec:
      serviceAccountName: ibm-cp4a-operator
      containers:
      - name: patterns-healthcheck
        image: quay.io/mikhail_nikitin1/cp4ba_health_check # image to pull
        command: ["/bin/bash"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        args: ["patterns_check.sh"] # per-job setting - can be core, options or patterns check
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cp4ba-healthcheck-options
  namespace: cp4ba
spec:
  template:
    spec:
      serviceAccountName: ibm-cp4a-operator
      containers:
      - name: options-healthcheck
        image: quay.io/mikhail_nikitin1/cp4ba_health_check # image to pull
        command: ["/bin/bash"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        args: ["options_check.sh"] # per-job setting - can be core, options or patterns check
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2