apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp4a-operator-catalog-subscription
  namespace: cp4ba
  annotations:
    argocd.argoproj.io/sync-wave: "250"
spec:
  channel: changeme_version
  name: ibm-cp4a-operator
  installPlanApproval: Automatic
  source: ibm-cp4a-operator-catalog
  sourceNamespace: cp4ba