apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  datasource_configuration:
    dc_gcd_datasource:
      dc_database_type: db2
      dc_common_gcd_datasource_name: GCD
      dc_common_gcd_xa_datasource_name: GCDXA
      database_servername: "c-db2-db2u.db2.svc.cluster.local"
      database_name: CP4BA
      database_port: "50000"
  ecm_configuration:
    fncm_secret_name: ibm-fncm-secret
    cpe:
      replica_count: 1
      cpe_production_setting:
        gcd_jndi_name: GCD
        gcd_jndixa_name: GCDXA
        license_model: FNCM.PVUNonProd
  initialize_configuration:
    ic_domain_creation:
      domain_name: P8DOMAIN
      encryption_key: 128
    ic_ldap_creation:
      ic_ldap_admin_user_name:
        - cpadmin
      ic_ldap_admins_groups_name:
        - cpadmins
      ic_ldap_name: ldap
  verify_configuration:
    vc_icn_verification:       
