apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  ecm_configuration:
    css:
      replica_count: 1
  initialize_configuration:
    ic_css_creation:
      - css_text_search_server_name: "icp4adeploy-css-1"
    ic_css_index_area:
      - object_store_name: OS1
        index_area_name: os1_index_area
    ic_enable_cbr:
      - object_store_name: OS1
  verify_configuration:
    vc_cpe_verification:
      vc_cpe_cbr:
        - cbr_cpe_obj_store_name: OS1  