apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  appVersion: 22.0.1
  shared_configuration:
    sc_deployment_platform: "ROKS" 
    sc_deployment_hostname_suffix: "cp4ba.itzroks-666000qmn3-nnxtkk-6ccd7f378ae819553d37d5f2ee142bd6-0000.au-syd.containers.appdomain.cloud"
    storage_configuration:
      sc_slow_file_storage_classname: "ibmc-file-gold-gid"
      sc_medium_file_storage_classname: "ibmc-file-gold-gid"
      sc_fast_file_storage_classname: "ibmc-file-gold-gid"
      sc_block_storage_classname: "ibmc-file-gold-gid"