apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  ecm_configuration:
    tm:
      replica_count: 1
      tm_production_setting:
        # Based on https://www.ibm.com/docs/en/enterprise-records/5.2.1?topic=in-configuring-content-navigator-task-manager-enterprise-records
        tm_job_url: "https://cpd-cp4ba.itzroks-666000qmn3-nnxtkk-6ccd7f378ae819553d37d5f2ee142bd6-0000.au-syd.containers.appdomain.cloud/ier/EnterpriseRecordsPlugin/IERApplicationPlugin.jar"
        security_roles_to_group_mapping:
          task_admins:
            groups: [cpadmins]
          task_users:
            groups: [cpusers]
          task_auditors:
            groups: [cpadmins]      
