apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-configuration
  namespace: cp4ba
spec:
  template:
    spec:
      serviceAccountName: cp4ba-sa
      containers:
      - name: init-certs
        image: quay.io/langley_millard_ibm/predeploy-certs # location the image is pushed to i.e. quay.io/langley_millard_ibm/repo_name
        command: ["./cert_gen.sh"]
        volumeMounts:
        - mountPath: /certificates
          name: cert-volume
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        imagePullPolicy: Always
      volumes:
      - name: cert-volume
        emptyDir: {}
      restartPolicy: OnFailure
  backoffLimit: 2