apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-configuration
  namespace: cp4ba
spec:
  template:
    spec:
      serviceAccountName: cp4ba-sa
      containers:
      - name: init-certs
        image: quay.io/langley_millard_ibm/predeploy-certs # location the image is pushed to i.e. quay.io/langley_millard_ibm/repo_name
        command: ["./cert_gen.sh"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
  # path to preconfigure job git repo https://github.com/oto-cp4ba-gitops/cp4ba-config-jobs
  # branch is origin/feature/multi-db-init-mn