apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets-mgr-ap-key
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgBHbnf1qdd0YhwMSkyYKoASi0IjCfpfquyBtBJoDNbZPaboyVP1LgANnILU6Uuea72euOzlNUVBj/qZSkZwYH5wT6lZn5ql+bJotqqOW0svnkukMDFObAVhdFYTi2odXYi5dkydVLl6JJEZd00cjaihnPwETI4dypag5s8Kp0AIzAR1ySqm1TUEkl9kX+y41GlJwUlOkrn7bWvPWi5oeodDinDAUPqx+g2jKjslRaosja6L5Dgs8HhI0bN8ao6rh4PuVu+jRHhis3f/z7l/yGS/dV66PTw/zeEDH+nbXBCJUr++DW0GY52QlAXjybkEfavox00n0Pj3sSUsXwKUq20GN6jdLLr5Bal8bBPdzpnVbmpufgVhHRj/Xl7NmmPC5mRudw1po/5h/tUZL6I79qrfpqX1+gjmjGkLPX/m1X/K0Z4JBtuql68TPB6rrKHXIe4CTI0IV8Az9/kLz2MQUWPXx6boONXTAj3WaEe3FInDw2euDf6cLJdOUiCDZYf5T3CpxItQr8fywFFGTKZsFRDB+SWVkXdBMsQl83+thLi9WA71YwAw8A19BX3Mr1omFcWxxsxp0612tNij0NkT8yj9E7RtLZ8BxO3Vg8OIEEkDwL1OP6lmp6Pf/6AFi82vhR7zXeIdRF+xUOyZ8h3s5mn5hQVRa8H1ypy0OvgVXh26L5i38L8W+LusXhlfaKz4AIzhL+kKT7bdibQwzESYKqBZHogr7xxYajb33behEhpulPJUhukJ6gwHGJhRpw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secrets-mgr-ap-key
      namespace: kube-system

