apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secrets-mgr-ap-key
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
<<<<<<< HEAD
        https://97732951-cd57-4dcf-9719-8e2a3778a324.au-syd.secrets-manager.appdomain.cloud
=======
        https://97732951-cd57-4dcf-9719-8e2a3778a324.au-syd.secrets-manager.appdomain.cloud
>>>>>>> 7ab6961f8cb9da1737bb83cfd234bf1e368fa59a
