apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            key: apiKey
            name: secrets-mgr-ap-key
            namespace: kube-system
      serviceUrl: >-
        https://97732951-cd57-4dcf-9719-8e2a3778a324.au-syd.secrets-manager.appdomain.cloud