apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            namespace: kube-system
            key: apiKey
      serviceUrl: >-
        https://97732951-cd57-4dcf-9719-8e2a3778a324.au-syd.secrets-manager.appdomain.cloud
