kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: db2

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: db2u-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'v2.0'