apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: db2u-operator
  namespace: db2
spec:
  channel: changeme
  installPlanApproval: Automatic
  name: db2u-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  # startingCSV: db2u-operator.v2.0.0