kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-marketplace

bases:
  - ../../base

patches:
  # templatise images in catalog sources - v22.1
  # catalog source
  - target:
      kind: CatalogSource
      name: ibm-cp4a-operator-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-cp-automation-catalog@sha256:f0b137d20ed52cc5bec8dd7ca03fe57e824cf30418803d421c6b50f4d7f5297e'

  # IBM Automation Foundation Base 1.3.7
  - target:
      kind: CatalogSource
      name: ibm-cp-automation-foundation-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-cp-automation-foundation-catalog@sha256:267bbc17bad1966be259bb9a6951c520c6fb824bfa42bbec22570ba49883d4ae'

 # IBM Automation Foundation Core 1.3.7
  - target:
      kind: CatalogSource
      name: ibm-automation-foundation-core-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-automation-foundation-core-catalog@sha256:5502c003afe7a0590ce123c3bbbd76e46374af641b3a210e3c25cfe2381e4647'

# IBM Cloud Foundational Services 3.19.0
  - target:
      kind: CatalogSource
      name: opencloud-operators
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-common-service-catalog@sha256:87904dee339ee4bbcbdc07949abc8df82bf6d85706f90795e6dae5e45f876b19'

# IBM Business Teams Service version 3.19.0
  - target:
      kind: CatalogSource
      name: bts-operator
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-bts-operator-catalog@sha256:68596113ad291b36b78d53207f73b53691f9f0154a21f38c717c08a0100deb9f'

# Cloud Native PostgresSQL 4.0.8
  - target:
      kind: CatalogSource
      name: cloud-native-postgresql-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:f3feb39b0dfb444a46d99a9cd160c616f8548d84d452cbc89e4985f0a2574486'