apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db2-pull-secret
  namespace: db2
spec: 
  data:
  - secretKey: ibmEntitlementKey
    remoteRef: 
      key: 18ba368d-18df-a2e5-bf20-73c862075a85
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: db2-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .ibmEntitlementKey | toString }}" }}   