apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: #ibm secret name
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 0d1d17a7-9d6b-a2b4-6b20-04d87f770fce
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: # ibm secret name
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ibmSecretNameinYaml: |-
          {{ "{{ .universalPassword | toString }}" }}
        nextSecretNameinYamk: |-
          {{ "{{ .universalPassword | toString }}" }}