apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-ban-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 60111497-8828-c776-2392-f89ce9a62ef7
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-ban-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        navigatorDBPassword: |-
          {{ .universalPassword | toString }}
        navigatorDBUsername: icndb
        keystorePassword: |-
          {{ .universalPassword | toString }}
        ltpaPassword: |- 
          {{ .universalPassword | toString }}
        appLoginUsername: cpadmin
        appLoginPassword: |-
          {{ .universalPassword | toString }}
        jMailUsername: cpadmin@cp.local
        jMailPassword: |-
          {{ .universalPassword | toString }}