apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-fncm-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 23761478-6fbb-c602-c388-9ff012702923
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-fncm-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        gcdDBUsername: gcd
        gcdDBPassword: |-
          {{ .universalPassword | toString }}
        os1DBUsername: os1
        os1DBPassword: |-
          {{ .universalPassword | toString }}
        appLoginUsername: cpadmin
        appLoginPassword: |-
          {{ .universalPassword | toString }}
        keystorePassword: |-
          {{ .universalPassword | toString }}
        ltpaPassword: |-
          {{ .universalPassword | toString }}
        fposDBUsername: fpos
        # https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/scripts/roles/cp4ba/tasks/predeploy/ier.yml
        # add additional secrets fields based  on apollo above - these particular fields are b64 encoded (the others dont appear to be. 
        # My guess is that these services decode the password )
        fposDBPassword: |-
          {{ .universalPassword | toString }}
        rosDBUsername: ros
        rosDBPassword: |-
          {{ .universalPassword | toString }}