apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-fncm-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 23761478-6fbb-c602-c388-9ff012702923
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-fncm-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        gcdDBUsername: gcd
        gcdDBPassword: |-
          {{ .universalPassword | toString }}
        os1DBUsername: os1
        os1DBPassword: |-
          {{ .universalPassword | toString }}
        appLoginUsername: cpadmin
        appLoginPassword: |-
          {{ .universalPassword | toString }}
        keystorePassword: |-
          {{ .universalPassword | toString }}
        ltpaPassword: |-
          {{ .universalPassword | toString }}