apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-entitlement-key
  namespace: cp4ba
spec: 
  data:
  - secretKey: ibmEntitlementKey
    remoteRef: 
      key: c1de98be-f05c-a8e3-9232-96d571db6895
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-entitlement-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ .ibmEntitlementKey | toString }}