apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-ier-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 53d53e56-c64e-9b75-4483-e493154e54a9
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-ier-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        keystorePassword: |-
          {{ "{{ .universalPassword | toString }}" }}