apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-ier-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 60111497-8828-c776-2392-f89ce9a62ef7
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-ier-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        keystorePassword: |-
          {{ .universalPassword | toString }}
        fposDBUsername: fpos
        # https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/scripts/roles/cp4ba/tasks/predeploy/ier.yml
        # add additional secrets fields based  on apollo above - these particular fields are b64 encoded (the others dont appear to be. 
        # My guess is that these services decode the password )
        fposDBPassword: |-
          {{ .universalPassword | toString }}
        rosDBUsername: ros
        rosDBPassword: |-
          {{ .universalPassword | toString }}