apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-bind-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 0678a623-77e9-1259-5b7c-3d9d4f32d0e3
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ldap-bind-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ldapUsername: cn=admin,dc=cp
        ldapPassword: |-
          {{ .adminPassword | toString }}