apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-bind-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 91e35fb6-d1bd-87c2-09bd-0715322e7c11
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ldap-bind-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ldapUsername: cn=admin,dc=cp
        ldapPassword: |-
          {{ .adminPassword | toString }}