apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-bind-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 23761478-6fbb-c602-c388-9ff012702923
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ldap-bind-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ldapUsername: cn=admin,dc=cp
        ldapPassword: |-
          "{{ .universalPassword | toString }}"