apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resource-registry-admin-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 23761478-6fbb-c602-c388-9ff012702923
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: resource-registry-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootPassword:  |-
          {{ .universalPassword | toString }}
        readUser: reader
        readPassword:  |-
          {{ .universalPassword | toString }}
        writeUser: writer
        writePassword:  |-
          {{ .universalPassword | toString }}