apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ierconfig
  namespace: cp4ba
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/timeout: 3000s
    router.openshift.io/sticky_cookie: -sticky_cookie_annotation
spec:
  to:
    kind: Service
    name: "icp4adeploy-cpe-svc"
  port:
    targetPort: http
  wildcardPolicy: None  