apiVersion: batch/v1
kind: Job
metadata:
  name: postdeploy-configuration
  namespace: cp4ba
spec:
  template:
    spec:
      containers:
      - name: postdeploy-configuration
        image: quay.io/langley_millard_ibm/<repo> # location the image is pushed to i.e. quay.io/langley_millard_ibm/repo_name
        command: ["./postdeploy_script"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        args: ["-i", "ZEN,IER,IER-TM,TM"]
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
  # path to preconfigure job git repo https://github.com/oto-cp4ba-gitops/cp4ba-config-jobs
  # branch is origin/feature/multi-db-init-mn