kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cp4ba

bases:
  - ../../base

patchesStrategicMerge:
  - rr.yaml
  - ban.yaml
  - cpe.yaml
  - css.yaml
  - tm.yaml
  - ier.yaml

# patchesJson6902:
#   - target:
#       kind: ICP4ACluster
#       name: icp4adeploy
#     path: patch.yaml
    