apiVersion: core.automation.ibm.com/v1beta1
kind: AutomationUIConfig
metadata:
  name: iaf-system
  namespace: cp4ba
spec:
  version: "v1"
  zenService:
    storageClass: "ibmc-file-gold-gid"
    zenCoreMetaDbStorageClass: "ibmc-file-gold-gid"