{{- if .Values.existingSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap
  namespace: openldap
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 0678a623-77e9-1259-5b7c-3d9d4f32d0e3
    - secretKey: configPassword
      remoteRef:
        key: c1b66a6e-7e93-f212-89b1-6e7699cfeea9
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: openldap
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LDAP_ADMIN_PASSWORD: |-
          {{ "{{ .adminPassword | toString }}" }}
        LDAP_CONFIG_PASSWORD: |-
          {{ "{{ .configPassword | toString }}" }}
{{- end }}